# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: bommel.xyz
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Markdown files converted to HTML upon checkin to Github using Jekyll..
baseurl: "/" # the subpath of your site, e.g. /blog note that it must _also_ be defined in classic-jekyll-theme.scss!
url: "https://pages.bommel.xyz" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: eelcovb
github_username:  m3ssage

data.setup.use-separate-banner-menubar-file: True #Used to determine if JQuery must be loaded.
data.setup.drop-down-menu: True #Used to determine if JQuery must be loaded.
data.setup.enable-cookies-policy: False #Used to determine if the cookies consent must be used.
google_analytics: True #Used to determine if google-analytics must be used.
