site_name: bommel.xyz
site_url: http://pages.bommel.xyz/
edit_uri: edit/main/docs/
site_description: Markdown site generated on github
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right  
  features:
    - announce.dismiss
  #  - navigation.tabs
    - navigation.sections
  #  - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: darkpurple
      accent: teal 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: purple
      accent: lime
plugins:
  - social
  - search
  - mkdocs-nav-weight  
  - tags
  - blog:
      blog_toc: true
      post_date_format: medium
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/m3ssage
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/eelcovb
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/eelcovb/
markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - tables
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg      