site_name: bommel.xyz
site_url: http://pages.bommel.xyz/
#edit_uri: edit/main/docs/
site_description: Markdown site generated on github
#nav:
#  - Blog: blog/index.md
#  - Archive: blog/archive/index.md
#  - Categories: blog/categories/index.md
#  - Tags: tags.md
#  - About: about.md

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  font:
    text: roboto
    code: roboto Mono
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right  
  features:
    - announce.dismiss
    - navigation.tabs
    - navigation.tabs.sticky
  #  - navigation.sections #use when you do not want the tree menu
  #  - toc.integrate
    - navigation.path
    - navigation.top
  #  - navigation.footer
    - navigation.indexes
    - navigation.expand
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: darkpurple
      accent: teal 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: purple
      accent: lime

plugins:
  - redirects:
      redirect_maps:
        'index.md': 'blog/index.md'
  - social
  - search
  - mkdocs-nav-weight  
  - tags
  - blog:
      blog_toc: true
      post_date_format: full
      archive_toc: true
      categories_toc: true
      pagination_format: "$link_first $link_previous ~2~ $link_next $link_last"
      pagination_keep_content: true
      draft_if_future_date: true

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/m3ssage
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/eelcovb
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/eelcovb/
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - tables
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg      
